# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 585ae64f4ae8fd498daf77242bcc2d9e33cdd5b6eb47a6cf2a21ea6814489be6a6fddf37393ad25734135590ec8c8a062696bb248fa8986a60add3b7426382e0

test:
  secret_key_base: 5c856d421c3b14ef5b4a5691c0fc5903bf2559ea3c02f71bbccb8b1dc65745b6efe97120f602bf2d9f166257f4cf37d65677c48bc10b962c1bdf9f622e383857

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
